### ISSUE TITLE
Fix zonal convergence of heat transport around peninsula [ Task 5]

### ISSUE THREAD

**Issue by adele157** [willaguiar/ASC_and_heat_transport#10]
We are calculating the cross-slope heat transport following the method in [Stewart et al. 2018](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2017GL075677), which adds the zonal convergence in a small longitude band on the shelf to the cross-isobath transport integrated in that same longitude band. This avoids the large cross-isobath heat transports that occur when the ASC crosses the isobath. However, this method does not work well around the peninsula (and in the western Ross Sea, anywhere else?), because a longitude band there covers a lot of length along the isobath, so we reduce our resolution in along-isobath space. We can fix this by using the meridional convergence in these regions instead of the zonal convergence.

**Comment by willaguiar** [comment]
I updated the heat transport code to bin the transport meridionally around the edge of the Ross sea, and in the East of the Antarctic Peninsula, and to calculate the meridional convergence in these locations. The new binning scheme separates the 1000m (gray contour) binning in three classes. 
Blue= where the coast is mostly zonal, so we bin the heat transport zonally, and calculate zonal convergence of heat on the shelf to close the budget of heat fluxes on the shelf bin.

Red = Where the coast is mostly meridional (Antarctic Peninsula and loop in Ross sea isobath). I calculated the meridional convergence of heat on the shelf to close the budget of heat fluxes on the shelf bin.

Green = We have open isobath boundaries zonally  (to the east of the Antarctic Peninsula) and meridionally (North of the Antarctic Peninsula). Here we have to calculate both the zonal convergence (Eastern  incoming heat flux - West outgoing heat flux), and meridional convergence (Southern incoming heat flux - Northern outgoing heat flux). In this location we just have one bin to simplify the calculation. 

Below are how the points are located in the new complex binning VS the older zonal binning. We  gain some points along the Antarctic peninsula (and can now analyze local cross-slope heat transport there)


![binnings_comparisson](https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/f97ce4e8-914b-4fba-a8f6-6fbc4b343be6)

**Comment by willaguiar** [comment]
**Below are how the heat transport and convergence changes between the new and old binning scheme**
It seems that on total the cross-slope heat transport, when adding the shelf convergence is the same [d], the only difference is that on the meridional coasts (Ross ~-170E, and AP ~-50W) the big jumps we had in heat transport are smaller when computing the meridional convergence ( you can see that in [b] too).
 one important thing is the old (purely zonal) convergence  amounts to almost 0 (~0.5 TW), while the new one (zonal + meridional) amounts to ~6TW.  I would expect it to be close to 0 instead of bigger. So perhaps I have to re-tweak the limits used for calculating the meridional convergence  for better closing the contour... or do you think having a total heat convergence different than 0 makes sense ? suggestions are welcome :)
![Convergenes_comparisson](https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/3c101e68-58d1-4a60-a554-fedff2acfd6b)

**Comment by willaguiar** [comment]
Closing issue.... We decided to stick to the Zonal convergence for these calculations.
