### ISSUE TITLE
Cross-slope heat transport calculation method

### ISSUE THREAD

**Issue by adele157** [willaguiar/ASC_and_heat_transport#11]
There are two obvious methods of computing the cross-slope heat transport:
1. Decompose the total heat transport at each point on the isobath into along-slope and across-slope components, i.e. following [Wilma's ASC method/code here](https://github.com/COSIMA/cosima-recipes/blob/master/DocumentedExamples/Cross-slope_section.ipynb).
2. Use the zonal or meridional (depending on the local orientation of the contour) heat transport across each segment of a contour that borders the edges of the tracer-grid, following [this notebook](https://github.com/COSIMA/cosima-recipes/blob/master/DocumentedExamples/Cross-contour_transport.ipynb). 
 
With method 2 we subsequently bin onto larger longitude bins and add the zonal convergence to remove the influence of the ASC crossing back and forth across the isobath. Possibly this extra step of adding the zonal convergence is not needed using method 1, because the ASC should already be decomposed into the along-slope rather than cross-slope component? I'm not sure.

It would be interesting to compute both methods and compare the spatial structure and magnitude of the cross slope heat transport.

**Comment by wghuneke** [comment]
The isobath definition for method 1 above is aimed to be closest to 1000 m, but can be deeper.
The definition for method 2 above us <= 1000 m and has no diagonal grid cells as closest neighbour.

**Comment by taimoorsohail** [comment]
Not sure if this is relevant but I had a thread with Maurice in the ACCESS-NRI Forum about this and he said he has written up a code that transforms T and S to be along- and across-isobath:

https://forum.access-hive.org.au/t/transforming-model-grid-to-along-and-cross-isobath/738

**Comment by willaguiar** [comment]
Here is a comparison of the Cross slope heat transport calculated with the speed in [i,j] space and [**a**long,**c**ross] space.


Total transports:
(a,c) space = -61.94 TW
(i,j) space = -61.71 TW

Below are both transports, before binning and before adding the zonal (along-slope) heat convergence. They seem quite similar where the isobath is zonal. When the isobath gets more meridional (Ross [-200,-250], Antarctic Peninsula [-100,-50]), then the transports differ. It makes sense since these places with a more _"inclined"_ isobath would probably have contamination from the zonal heat convergence when calculating the HT on (i,j) space.

 
<img width="581" alt="Screen Shot 2023-06-15 at 2 47 32 PM" src="https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/66fa4ede-e1bc-4b0a-8e79-b4414f2bd597">





In the HT(i,j) calculations, the zonal heat  convergence has to be added to the heat transport to remove the effect of the ASC crossing the isobath sequentially. This is often done by binning the cross-slope heat transport  (HT) in longitude bins, calculating the convergence of heat transport as the difference of the zonal transport in the east-west edges of these bins, and then adding this convergence to the binned HT in each particular bin. (Quite complicated to explain, but maybe I can draw something more clear in the next meeting). 

I did a similar thing with the HT(a,c), but binned HT along the contour distance from the initial point (in -280 W, 0km) instead of along the longitude. HT+convergence (a,c) is similar to the HT(i,j) without discounting the heat convergence, which suggest that since the transport components are already rotated in (arc) we don’t need to add the zonal heat convergence to the calculations.  Also, HT(a,c) is relatively similar to HT+convergence (i,j).

<img width="877" alt="Screen Shot 2023-06-15 at 4 34 48 PM" src="https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/92b030a5-bcba-4812-9983-93186fded1c2">

For the plot above I used `bin_width = 35  km, bin_spacing = 13 km`

 So if we start using the HT(a, c) method we might not need to discount heat convergence as Adele suggested. What are y'all thoughts?

**Comment by willaguiar** [comment]
Spatially, we have a little more variability when we calculate the HT(a,c) then on HT + convergence (i,j). The distance used for the binning can smooth a lot the spatial variability. When we bin the transports into really large 350 km bins,  the transport directions seem to start aligning with the ASC classifications from Huneke (2021), with poleward transport aligned with bottom-intensified ASC, and equatorialward aligned with surface intensified ASC.

<img width="709" alt="Screen Shot 2023-06-16 at 12 42 07 PM" src="https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/cd7bd00f-2bde-49b4-ab9e-17d199e8d104">

**Comment by wghuneke** [comment]
Hi, I'm not sure if I follow/agree with your argumentation regarding the need for adding "zonal" convergence. It's not super obvious to me that HT(a,c) is similar to HT(i,j)+conv. It's true that the along/cross space accounts for the "true" cross-slope components, but the ASC might still cross the isobath across which you calculate the heat transport. I might be wrong though...

**Comment by willaguiar** [comment]
Closing this issue. We decided to use the (i,j) grid method for that, instead of the Along/across. We just need to interpolate the ASC speed into the HT stepwise grid (which is currently done in the codes ending with XYgrid.py).
