### ISSUE TITLE
Reduce bin size when longitude-binning CSHT and U_along

### ISSUE THREAD

**Issue by taimoorsohail** [willaguiar/ASC_and_heat_transport#32]
To better reflect the range of depths of the 1000m isobath, we need to reduce the width of the longitude bins (which are currently 1/4-degree) that we use for the longitude binning of the CSHT and U_along array. We should test what impact this reduced bin width has on the layer-wise correlation between CSHT+ZC vs U_along. If not a huge difference, we can go ahead with the profile normalisation of these finer bins for use in the analysis, as discussed in #31.

**Comment by taimoorsohail** [comment]
@willaguiar do you have the code for the binning/are you able to produce a finer binned CSHT+ZC and U_along field? This would help in checking this.

**Comment by willaguiar** [comment]
Yep, sure :).  I can easily change the binning by re-running the CSHT code with different bin widths.  Ill do it for a sample year for comparisson

**Comment by willaguiar** [comment]
Here are some tests for CSHT with different bin widths (1:0.5:3$deg).

___________
Vertical sum
![image](https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/9e36205d-4d84-431f-b335-02e94fd99f85)

Bin size don't change much the CSHT along the contour ( just larger bins have smoother curves)

______
CSHT(bins,z)... I doesn't matter the bin width, the deep values of ZC between 61W and 55W (grey bars) are always there......
**CSHT alone:**
![image](https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/85b1eb09-1282-478d-94ba-ec0d60d34e33)

**CSHT + ZC:**
![image](https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/d7323190-04e5-4cdf-af50-078c9ea0f8fe)


______
Bathymetry between 61W and 55W (below)
We have a deep trough in around 62.5S, south of the isobath. Because ZC vales are integrated  meridionally from the isobath until the continent, these deep troughs would add ZC in the deep layers we see in the plots above.  Some possible solutions would be:

A- Squashing ZC at layers deeper than the isobath, to the deepest isobath depth ( 2000mZC added to the 1200m CSHT instead).
B-Disregard the zonal convergence, as [we found that has lower impact on the CSHT correlations with ASC, when integrated over the regimes](https://github.com/willaguiar/ASC_and_heat_transport/issues/21#issuecomment-1786453801)

![image](https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/7895f448-ca2c-4258-8fbb-61c508bcba33)

**Comment by willaguiar** [comment]
In the last meeting, we discussed that the issue was actually the shallow bathymetry is misrepresented in the longitude binned data (e.g., -150). However, as we are moving into analyzing the CSHT in density space now, this will not be a problem anymore. So closing this issue temporarily....
